- name: Install NGINX
  apt:
    name: nginx
    state: present

- name: Copy NGINX config
  template:
    src: yii2-nginx.conf.j2
    dest: /etc/nginx/sites-available/yii2

- name: Enable NGINX config
  file:
    src: /etc/nginx/sites-available/yii2
    dest: /etc/nginx/sites-enabled/yii2
    state: link
    force: yes

- name: Remove default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Restart NGINX
  service:
    name: nginx
    state: restarted

