- name: Install Docker
  apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Enable and start Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: '0755'

- name: Init Docker Swarm
  shell: docker swarm init
  ignore_errors: true

