name: Deploy Yii2 App
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Image
        run: |
          docker build -t ashutosh1999/yii2-app:latest .
          docker push ashutosh1999/yii2-app:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo docker pull ashutosh1999/yii2-app:latest

            if ! sudo docker service inspect yii2_app >/dev/null 2>&1; then
              echo "Service not found, creating new service..."
              sudo docker service create \
                --name yii2_app \
                --publish 80:80 \
                --replicas 1 \
                ashutosh1999/yii2-app:latest
            else
              echo "Service exists, updating..."
              sudo docker service update \
                --image ashutosh1999/yii2-app:latest \
                yii2_app
            fi
            
            echo "Current service status:"
            sudo docker service ps yii2_app
